# Generated by Django 3.0.8 on 2020-08-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200801_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={},
        ),
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['created', 'pk']},
        ),
    ]
