# Generated by Django 3.0.8 on 2020-07-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Price incl. Tax'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_currency',
            field=models.CharField(default='INR', max_length=12, verbose_name='Currency'),
        ),
    ]
