# Generated by Django 3.0.8 on 2020-08-01 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20200731_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_currency',
            new_name='currency',
        ),
    ]
